FROM gcc:14.2-bookworm

RUN useradd -m myuser

COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh && chown myuser:myuser /usr/local/bin/run.sh

RUN chmod 555 /usr/local/bin/run.sh

WORKDIR /home/myuser
RUN chown myuser:myuser /home/myuser

USER myuser

ENTRYPOINT ["/usr/local/bin/run.sh", "cpp"]
