FROM rust:1.84.1-alpine3.20

RUN adduser -D myuser

COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh && chown myuser:myuser /usr/local/bin/run.sh

RUN chmod 555 /usr/local/bin/run.sh

WORKDIR /home/myuser
RUN chown myuser:myuser /home/myuser

USER myuser

ENTRYPOINT ["/usr/local/bin/run.sh", "rust"]
