FROM golang:1.23-alpine

# Create a new non-privileged user
RUN adduser -D myuser

# Copy the script to the container and set correct permissions
COPY run.sh /usr/local/bin/run.sh
RUN chmod +x /usr/local/bin/run.sh && chown myuser:myuser /usr/local/bin/run.sh

# Set permissions for the run.sh to be read-only for non-root users
RUN chmod 555 /usr/local/bin/run.sh

# Set the working directory and change ownership of working directory
WORKDIR /home/myuser
RUN chown myuser:myuser /home/myuser

# Switch to the non-privileged user
USER myuser

# Set the entry point for the container
ENTRYPOINT ["/usr/local/bin/run.sh", "go"]
